stages:
    - build_front
    - deploy_front

build webapp:
    image: node:16-alpine
    stage: build_front
    script: 
        - cd frontend
        - yarn install
        - yarn build
    artifacts:
        paths:
            - frontend/build
    only:
        - frontendmain

deploy front:
    stage: deploy_front
    image:
        name: amazon/aws-cli:2.4.11
        entrypoint: [""]
    script:
        - aws --version
        - aws s3 sync frontend/build s3://homespot.ddns.net --delete
    only:
        - frontendmain
