stages:
    # - test 
    # - build
    - build
    # - deploy
    - deploy

# test website:
#     stage : test
#     image: node:15
#     script:
#         - yarn install
#         - yarn build

# build website:
#     stage: build
#     image: node:15
#     script:
#         - cd frontend
#         - npm run build
#     paths:
#         - frontend/build
#     only:
#         - main

build:
    stage: build
    image:  maven:latest
    script:
        - cd backend
        - cd HomeSpot
        - ls
        - echo "Building app..."
        - mvn clean install
        - echo "Finished building the app."
    artifacts:
        expire_in: 1 week
        paths:
            - backend/DigitalBooking/target/consoleapp-2.7.2.jar
    only:
        - main

deploy:
    stage: deploy
    image: alpine:3.11
    before_script:
        - apk update && apk add openssh-client bash
        - mkdir -p ~/.ssh
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
        - touch ~/.ssh/config
        - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
        - ssh-keyscan -H $DEPLOY_SERVER_IP >> ~/.ssh/known_hosts
    script:
        - echo "Deploying started..."
        - ssh ubuntu@$DEPLOY_SERVER_IP "sudo systemctl stop consoleapp.service"
        - scp ./backend/DigitalBooking/target/consoleapp-2.7.2.jar ubuntu@$DEPLOY_SERVER_IP:~/console-app/
        - ssh ubuntu@$DEPLOY_SERVER_IP "sudo systemctl start consoleapp.service"
        - echo "Finished deploying the app."
    only:
        - main
