// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Sprint4Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void registerwhitinvalidemail() {
    driver.get("http://homespot-frontend-app.s3-website.ca-central-1.amazonaws.com/");
    driver.findElement(By.cssSelector(".containerButton > button:nth-child(1)")).click();
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("Mónica");
    driver.findElement(By.name("surname")).click();
    driver.findElement(By.name("surname")).sendKeys("Bernal");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("mohd.com");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("mok123");
    driver.findElement(By.name("confirmPassword")).click();
    driver.findElement(By.name("confirmPassword")).sendKeys("mok123");
    driver.findElement(By.cssSelector("button:nth-child(5)")).click();
    driver.switchTo().alert().dismiss();
  }
  @Test
  public void succesFulLogIn() {
    driver.get("http://homespot-frontend-app.s3-website.ca-central-1.amazonaws.com/");
    driver.findElement(By.cssSelector(".containerButton > button:nth-child(1)")).click();
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("Mónica");
    driver.findElement(By.name("surname")).click();
    driver.findElement(By.name("surname")).sendKeys("Bernal");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("mok2710@hotmail.com");
    driver.findElement(By.name("password")).click();
    driver.findElement(By.name("password")).sendKeys("mok123");
    driver.findElement(By.name("confirmPassword")).click();
    driver.findElement(By.name("confirmPassword")).sendKeys("mok123");
    driver.findElement(By.cssSelector("button:nth-child(5)")).click();
  }
  @Test
  public void uRLNavigation() {
    driver.get("http://homespot-frontend-app.s3-website.ca-central-1.amazonaws.com/");
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".buttonLogIn"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//button[contains(.,\'Crear cuenta\')]"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector(".containerButton > button:nth-child(1)")).click();
    {
      WebElement element = driver.findElement(By.name("name"));
      Boolean isEditable = element.isEnabled() && element.getAttribute("readonly") == null;
      assertTrue(isEditable);
    }
    {
      WebElement element = driver.findElement(By.name("surname"));
      Boolean isEditable = element.isEnabled() && element.getAttribute("readonly") == null;
      assertTrue(isEditable);
    }
    {
      WebElement element = driver.findElement(By.name("email"));
      Boolean isEditable = element.isEnabled() && element.getAttribute("readonly") == null;
      assertTrue(isEditable);
    }
    {
      WebElement element = driver.findElement(By.name("confirmPassword"));
      Boolean isEditable = element.isEnabled() && element.getAttribute("readonly") == null;
      assertTrue(isEditable);
    }
    throw new Error("`submit` is not a supported command in Selenium WebDriver. Please re-record the step in the IDE.");
    driver.findElement(By.linkText("Iniciar sesion")).click();
    driver.findElement(By.linkText("Registrar")).click();
    driver.findElement(By.cssSelector(".initialContainer > img")).click();
  }
  @Test
  public void findaproductbycity() {
    driver.get("http://homespot-frontend-app.s3-website.ca-central-1.amazonaws.com/");
    driver.findElement(By.cssSelector(".css-8mmkcg")).click();
    driver.findElement(By.cssSelector("#react-select-2-option-0 > .selectLocation")).click();
    driver.findElement(By.cssSelector(".search")).click();
    driver.findElement(By.cssSelector(".title:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".title:nth-child(1)")).click();
  }
  @Test
  public void productandfeatures() {
    driver.get("http://homespot-frontend-app.s3-website.ca-central-1.amazonaws.com/");
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".title:nth-child(1)"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector("div:nth-child(1) > .sc-jSMfEi img")).click();
    assertThat(driver.findElement(By.cssSelector(".sc-papXJ:nth-child(1) > .cardProduct .category")).getText(), is("Departamento"));
    driver.findElement(By.cssSelector("div:nth-child(2) > .sc-jSMfEi img")).click();
    assertThat(driver.findElement(By.cssSelector(".sc-papXJ:nth-child(1) > .cardProduct .category")).getText(), is("Casa de playa"));
    driver.findElement(By.cssSelector("div:nth-child(3) #collapseOne > img")).click();
    assertThat(driver.findElement(By.cssSelector(".sc-papXJ:nth-child(1) > .cardProduct .category")).getText(), is("Cabaña"));
    driver.findElement(By.cssSelector("div:nth-child(4) > .sc-jSMfEi img")).click();
    assertThat(driver.findElement(By.cssSelector(".sc-papXJ:nth-child(1) > .cardProduct .category")).getText(), is("Casa"));
    driver.findElement(By.cssSelector(".showAll")).click();
    driver.findElement(By.cssSelector(".sc-ftvSup:nth-child(1) .verMas")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".descriptionTitle"));
      assert(elements.size() > 0);
    }
    driver.findElement(By.cssSelector(".images")).click();
    driver.findElement(By.cssSelector(".styles-module_close__2I1sI")).click();
    js.executeScript("window.scrollTo(0,700)");
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("a > button"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void selectdatesforbooking() {
    driver.get("http://homespot-frontend-app.s3-website.ca-central-1.amazonaws.com/");
    driver.findElement(By.cssSelector(".css-8mmkcg")).click();
    driver.findElement(By.cssSelector("#react-select-2-option-0 > .selectLocation")).click();
    driver.findElement(By.cssSelector(".inputBox")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".rdrDayToday"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".rdrDayNumber:nth-child(2) > span")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".rdrDay:nth-child(13)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".search")).click();
  }
  @Test
  public void navigationtobooking() {
    driver.get("http://homespot-frontend-app.s3-website.ca-central-1.amazonaws.com/");
    driver.findElement(By.cssSelector(".sc-papXJ:nth-child(1) > .cardProduct .verMas")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector("a > button")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("Mónica");
    driver.findElement(By.name("surname")).click();
    driver.findElement(By.name("surname")).sendKeys("Bernal");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("mok2710@hotmail.com");
    driver.findElement(By.name("password")).sendKeys("mok123");
    driver.findElement(By.name("confirmPassword")).click();
    driver.findElement(By.name("confirmPassword")).sendKeys("mok123");
    driver.findElement(By.cssSelector("button:nth-child(5)")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".submit"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".label:nth-child(1) > div:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".label:nth-child(1) > input")).click();
    driver.findElement(By.cssSelector(".label:nth-child(1) > input")).sendKeys("mok2710@hotmail.com");
    driver.findElement(By.cssSelector(".label:nth-child(2) > input")).sendKeys("mok123");
    driver.findElement(By.cssSelector(".submit")).click();
    driver.findElement(By.cssSelector(".sc-papXJ:nth-child(1) > .cardProduct .verMas")).click();
    js.executeScript("window.scrollTo(0,0)");
    js.executeScript("window.scrollTo(0,600)");
    driver.findElement(By.cssSelector("a > button")).click();
    js.executeScript("window.scrollTo(0,212)");
    driver.findElement(By.cssSelector(".label:nth-child(4) > input")).click();
    driver.findElement(By.cssSelector(".label:nth-child(4) > input")).sendKeys("TAMPA");
    driver.findElement(By.id("cardSelect")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".selectLabel"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("react-select-4-option-1"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".select")).click();
    driver.findElement(By.id("react-select-4-option-4")).click();
    driver.findElement(By.cssSelector(".submit")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".rdrMonth:nth-child(2) .rdrDay:nth-child(21) > .rdrDayNumber > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
  }
  @Test
  public void shortpassword() {
    driver.get("http://homespot-frontend-app.s3-website.ca-central-1.amazonaws.com/");
    driver.manage().window().setSize(new Dimension(1936, 1048));
    driver.findElement(By.cssSelector(".containerButton > button:nth-child(1)")).click();
    driver.findElement(By.name("name")).click();
    driver.findElement(By.name("name")).sendKeys("Mónica");
    driver.findElement(By.name("surname")).click();
    driver.findElement(By.name("surname")).sendKeys("Bernal");
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("mok2710@hotmail.com");
    driver.findElement(By.name("password")).sendKeys("mok123");
    driver.findElement(By.cssSelector("section")).click();
    driver.findElement(By.name("password")).sendKeys("123");
    driver.findElement(By.name("confirmPassword")).click();
    driver.findElement(By.name("confirmPassword")).sendKeys("123");
    driver.findElement(By.cssSelector("button:nth-child(5)")).click();
    assertThat(driver.findElement(By.cssSelector(".error")).getText(), is("La contraseña debe tener al menos 6 caracteres"));
  }
  @Test
  public void bookingasUser() {
    driver.get("http://homespot-frontend-app.s3-website.ca-central-1.amazonaws.com/");
    driver.manage().window().setSize(new Dimension(1050, 652));
    driver.findElement(By.cssSelector(".sc-papXJ:nth-child(2) .verMas")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".calendarElement .rdrMonthPicker > select")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".calendarElement .rdrMonthPicker > select"));
      dropdown.findElement(By.xpath("//option[. = 'October']")).click();
    }
    js.executeScript("window.scrollTo(0,1076)");
    driver.findElement(By.cssSelector(".rdrDayHovered > .rdrDayNumber")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".rdrCalendarWrapper:nth-child(3) .rdrDay:nth-child(14) > .rdrDayNumber > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".rdrDayHovered > .rdrDayNumber > span")).click();
    driver.findElement(By.cssSelector("a > button")).click();
    js.executeScript("window.scrollTo(0,1349.3333740234375)");
    driver.findElement(By.cssSelector(".label:nth-child(4) > input")).click();
    driver.findElement(By.cssSelector(".label:nth-child(4) > input")).sendKeys("TAMPA");
    js.executeScript("window.scrollTo(0,600)");
    driver.findElement(By.cssSelector(".calendarElement .rdrMonthPicker > select")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".calendarElement .rdrMonthPicker > select"));
      dropdown.findElement(By.xpath("//option[. = 'October']")).click();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".calendarElement .rdrDay:nth-child(18) > .rdrDayNumber"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".rdrDayHovered > .rdrDayNumber")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".calendarElement .rdrDay:nth-child(14)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".rdrDayHovered > .rdrDayNumber > span")).click();
    driver.findElement(By.cssSelector(".css-qc6sy-singleValue")).click();
    driver.findElement(By.id("react-select-3-option-4")).click();
    driver.findElement(By.cssSelector(".submit")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".submit"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".swal-button--confirm")).click();
    js.executeScript("window.scrollTo(0,1028.6666259765625)");
    driver.findElement(By.cssSelector(".swal-button")).click();
  }
  @Test
  public void succesFulRegistration() {
    driver.get("http://homespot-frontend-app.s3-website.ca-central-1.amazonaws.com/");
    driver.manage().window().setSize(new Dimension(1050, 652));
    {
      WebElement element = driver.findElement(By.cssSelector(".initialContainer > img"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".buttonLogIn")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("button:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("mok2710@hotmail.com");
    driver.findElement(By.name("password")).sendKeys("mok123");
    driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    js.executeScript("window.scrollTo(0,0)");
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div[@id=\'root\']/div/header/div[2]/div[2]/div"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div[@id=\'root\']/div/header/div[2]/div/div"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void renderofcategory() {
    driver.get("http://homespot-frontend-app.s3-website.ca-central-1.amazonaws.com/");
    driver.manage().window().setSize(new Dimension(1050, 652));
    driver.findElement(By.cssSelector("div:nth-child(1) > .sc-jSMfEi img")).click();
    driver.findElement(By.cssSelector("div:nth-child(2) > .sc-jSMfEi h2")).click();
    driver.findElement(By.cssSelector("div:nth-child(4) h2")).click();
    driver.findElement(By.cssSelector("div:nth-child(3) .label")).click();
  }
  @Test
  public void screensize() {
    driver.get("http://homespot-frontend-app.s3-website.ca-central-1.amazonaws.com/");
    driver.manage().window().setSize(new Dimension(375, 667));
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div[3]"));
      assert(elements.size() > 0);
    }
    driver.manage().window().setSize(new Dimension(768, 1024));
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".buttonLogIn"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".containerButton > button:nth-child(1)"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void selectcityanddateandclickfind() {
    driver.get("http://homespot-frontend-app.s3-website.ca-central-1.amazonaws.com/");
    driver.manage().window().setSize(new Dimension(1280, 672));
    {
      WebElement element = driver.findElement(By.cssSelector(".showAll"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".css-8mmkcg")).click();
    driver.findElement(By.id("react-select-2-option-1")).click();
    driver.findElement(By.cssSelector(".inputBox")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".rdrDay:nth-child(27) > .rdrDayNumber"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".rdrDay:nth-child(25) > .rdrDayNumber > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".rdrDay:nth-child(26) > .rdrDayNumber > span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".rdrDayNumber:nth-child(2) > span")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".rdrDay:nth-child(28)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".container")).click();
    driver.findElement(By.cssSelector(".inputBox")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".rdrDay:nth-child(26)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".rdrDayNumber:nth-child(2) > span")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".rdrDay:nth-child(26)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".rdrDay:nth-child(32) > .rdrDayNumber"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".rdrDays")).click();
    driver.findElement(By.cssSelector(".search")).click();
  }
  @Test
  public void nobookingwithoutregister() {
    driver.get("http://homespot-frontend-app.s3-website.ca-central-1.amazonaws.com/");
    driver.manage().window().setSize(new Dimension(1296, 688));
    driver.findElement(By.cssSelector("div:nth-child(1) > .sc-jSMfEi h2")).click();
    driver.findElement(By.cssSelector("div:nth-child(2) > .sc-jSMfEi h2")).click();
    driver.findElement(By.cssSelector("div:nth-child(3) .label")).click();
    driver.findElement(By.cssSelector(".sc-papXJ:nth-child(1) > .cardProduct .verMas")).click();
    js.executeScript("window.scrollTo(0,0)");
    js.executeScript("window.scrollTo(0,6)");
    driver.findElement(By.cssSelector("a > button")).click();
    js.executeScript("window.scrollTo(0,0)");
    {
      List<WebElement> elements = driver.findElements(By.name("email"));
      assert(elements.size() > 0);
    }
    {
      List<WebElement> elements = driver.findElements(By.name("password"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void bookingdenied() {
    driver.get("http://homespot-frontend-app.s3-website.ca-central-1.amazonaws.com/");
    driver.manage().window().setSize(new Dimension(1050, 652));
    driver.findElement(By.cssSelector(".sc-papXJ:nth-child(2) .verMas")).click();
    js.executeScript("window.scrollTo(0,0)");
    js.executeScript("window.scrollTo(0,141.3333282470703)");
    driver.findElement(By.xpath("//div[@id=\'root\']/div/section/div[2]/div[2]/a/button")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div[@id=\'root\']/div/section/section/div[2]"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void loginAsAdmin() {
    driver.get("http://homespot-frontend-app.s3-website.ca-central-1.amazonaws.com/");
    driver.manage().window().setSize(new Dimension(1050, 652));
    driver.findElement(By.cssSelector(".buttonLogIn")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("button:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("testAdmin@gmail.com");
    driver.findElement(By.name("password")).sendKeys("123456");
    driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    js.executeScript("window.scrollTo(0,0)");
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div[@id=\'root\']/div/header/div[2]/div[2]/div"));
      assert(elements.size() > 0);
    }
  }
  @Test
  public void createabooking() {
    driver.get("http://homespot-frontend-app.s3-website.ca-central-1.amazonaws.com/");
    driver.findElement(By.cssSelector(".buttonLogIn")).click();
    driver.findElement(By.name("email")).click();
    driver.findElement(By.name("email")).sendKeys("testAdmin@gmail.com");
    driver.findElement(By.name("password")).sendKeys("123456");
    driver.findElement(By.cssSelector("button:nth-child(3)")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".admibtn:nth-child(4)")).click();
    driver.findElement(By.cssSelector(".boxProduct:nth-child(4)")).click();
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("Alaska");
    driver.findElement(By.cssSelector("div:nth-child(2) > .title2 > .form-control")).click();
    driver.findElement(By.cssSelector("div:nth-child(2) > .title2 > .form-control")).sendKeys(" a30 minutos del aeropuerto, y a 20 del aerpuerto ");
    driver.findElement(By.cssSelector(".boxButton > button")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".css-ackcql")).click();
    driver.findElement(By.cssSelector("#react-select-4-option-2 .cities")).click();
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("calle 123");
    driver.findElement(By.cssSelector("button:nth-child(6)")).click();
    driver.findElement(By.cssSelector(".icon:nth-child(1) > .MuiSvgIcon-root")).click();
    driver.findElement(By.id("grill")).click();
    driver.findElement(By.cssSelector(".icon:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".icon:nth-child(4) > .MuiSvgIcon-root")).click();
    driver.findElement(By.id("laundry")).click();
    driver.findElement(By.id("wifi")).click();
    driver.findElement(By.id("ac")).click();
    driver.findElement(By.id("pets")).click();
    driver.findElement(By.id("text")).click();
    driver.findElement(By.id("text")).click();
    driver.findElement(By.id("text2")).click();
    driver.findElement(By.id("text2")).sendKeys("fgvdfg");
    driver.findElement(By.cssSelector("label:nth-child(3) > #text2")).click();
    driver.findElement(By.cssSelector("label:nth-child(3) > #text2")).sendKeys("gfgd");
    driver.findElement(By.cssSelector("label:nth-child(4) > #text2")).click();
    driver.findElement(By.cssSelector("label:nth-child(4) > #text2")).sendKeys("g");
    driver.findElement(By.xpath("(//textarea[@id=\'text\'])[3]")).click();
    driver.findElement(By.xpath("(//textarea[@id=\'text\'])[3]")).sendKeys("dgdf");
    driver.findElement(By.cssSelector("label:nth-child(9)")).click();
    driver.findElement(By.cssSelector("label:nth-child(9)")).click();
    {
      WebElement element = driver.findElement(By.xpath("(//textarea[@id=\'text\'])[5]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.xpath("(//textarea[@id=\'text\'])[5]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.xpath("(//textarea[@id=\'text\'])[5]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.xpath("(//textarea[@id=\'text\'])[5]")).click();
    driver.findElement(By.xpath("(//textarea[@id=\'text\'])[5]")).sendKeys("ggdg");
    driver.findElement(By.cssSelector("label:nth-child(7)")).click();
    driver.findElement(By.xpath("(//textarea[@id=\'text\'])[4]")).click();
    driver.findElement(By.xpath("(//textarea[@id=\'text\'])[4]")).sendKeys("fdgdghrth");
    driver.findElement(By.xpath("(//textarea[@id=\'text\'])[2]")).click();
    driver.findElement(By.xpath("(//textarea[@id=\'text\'])[2]")).sendKeys("thrhswhsty");
    driver.findElement(By.id("text")).click();
    driver.findElement(By.id("text")).sendKeys("kuykyuk");
    driver.findElement(By.cssSelector("button:nth-child(5)")).click();
    driver.findElement(By.cssSelector("div:nth-child(2) > .form-control")).click();
    driver.findElement(By.cssSelector("div:nth-child(2) > .form-control")).sendKeys("0");
    driver.findElement(By.cssSelector("div:nth-child(2) > .form-control")).click();
    driver.findElement(By.cssSelector("div:nth-child(2) > .form-control")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("div:nth-child(2) > .form-control"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("div:nth-child(2) > .form-control")).click();
    driver.findElement(By.cssSelector("div:nth-child(2) > .form-control")).click();
    driver.findElement(By.cssSelector("div:nth-child(2) > .form-control")).sendKeys("0.01");
    driver.findElement(By.cssSelector("div:nth-child(2) > .form-control")).click();
    driver.findElement(By.cssSelector("div:nth-child(2) > .form-control")).sendKeys("0.02");
    driver.findElement(By.cssSelector("div:nth-child(2) > .form-control")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("div:nth-child(2) > .form-control"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("div:nth-child(2) > .form-control")).sendKeys("0.03");
    driver.findElement(By.cssSelector("div:nth-child(2) > .form-control")).click();
    driver.findElement(By.cssSelector("div:nth-child(3) > .form-control")).click();
    driver.findElement(By.cssSelector("div:nth-child(3) > .form-control")).sendKeys("5");
    driver.findElement(By.cssSelector("div:nth-child(3) > .form-control")).click();
    driver.findElement(By.cssSelector("div:nth-child(3) > .form-control")).sendKeys("10");
    driver.findElement(By.cssSelector("div:nth-child(3) > .form-control")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("div:nth-child(3) > .form-control"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("div:nth-child(3) > .form-control")).sendKeys("15");
    driver.findElement(By.cssSelector("div:nth-child(3) > .form-control")).click();
    driver.findElement(By.cssSelector("div:nth-child(3) > .form-control")).sendKeys("20");
    driver.findElement(By.cssSelector("div:nth-child(3) > .form-control")).click();
  }
}
